=== Sokolover/jwd/module1/src/main/resources/xml/gemSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://sokolov.com/gem"
           targetNamespace="http://sokolov.com/gem"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="gems">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="gem" type="gemType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="gemType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="preciousness" type="xs:string"/>
            <xs:element name="origin" type="xs:string"/>
            <xs:element name="visualParams" type="paramsType"/>
            <xs:element name="value" type="xs:int"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="paramsType">
        <xs:sequence>
            <xs:element name="color" type="xs:string"/>
            <xs:element name="transparency" type="xs:int"/>
            <xs:element name="numberOfFaces" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== Sokolover/jwd/module1/task3/src/main/resources/xml/gem.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gems xmlns="http://sokolov.com/gem"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="gemSchema.xsd">

    <gem id="id-1">
        <name>brilliant</name>
        <preciousness>precious</preciousness>
        <origin>Africa</origin>
        <visualParams>
            <color>white</color>
            <transparency>90</transparency>
            <numberOfFaces>12</numberOfFaces>
        </visualParams>
        <value>3</value>
    </gem>

    <gem id="id-2">
        <name>amethyst</name>
        <preciousness>semiprecious</preciousness>
        <origin>Russia</origin>
        <visualParams>
            <color>purple</color>
            <transparency>50</transparency>
            <numberOfFaces>5</numberOfFaces>
        </visualParams>
        <value>5</value>
    </gem>

</gems>
